name: release

on:
  release:
    types: [published]

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v3
    - name: print out github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      - name: list all github action env vars
        run: env
      - name: build artifacts
        run: echo *
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .gerbil/bin/slack
          asset_name: slack
