on:
  push:
    tags:
      - '*'

- name: build artifacts
    run: make
  - name: upload linux artifact
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ github.token }}
    with:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      asset_path: .gerbil/bin/slack
      asset_name: slack
